[package]
name = "visdom"
version = "0.1.0"
edition = "2018"
description = "A html document operation library written in Rust, like Nodejs library `cheerio`, they both used API like jQuery."
keywords = ["html-parser", "jQuery-api", "querySelectorAll", "crawl"]
authors = ["jxz_211 <jxz_211@163.com>"]
repository = "https://github.com/fefit/visdom"
categories = ["web-programming"]
license = "MIT"
exclude = [".vscode/*.*", ".editorconfig", ".travis.yml", "src/main.rs"]

[dependencies]
mesdoc = "0.1.6"
rphtml = "0.3.6"
# mesdoc = { path = "../mesdoc" }
# rphtml = { path = "../rphtml"}

[dev-dependencies]
crossbeam = "0.8.0"
criterion = "0.3.3"

[[bench]]
name = "benchmark"
harness = false