[package]
name = "visdom"
version = "0.0.7"
authors = ["jxz_211 <jxz_211@163.com>"]
edition = "2018"

[dependencies]
ntree = { git = "https://github.com/fefit/ntree", tag = "v0.1.0" }
rphtml = { git = "https://github.com/fefit/rphtml", tag = "v0.3.3" }
# ntree = { path = "../ntree" }
# rphtml = { path = "../rphtml" }

[dev-dependencies]
crossbeam = "0.8.0"
criterion = "0.3.3"

[[bench]]
name = "benchmark"
harness = false