[package]
name = "visdom"
version = "0.0.1"
authors = ["jxz_211 <jxz_211@163.com>"]
edition = "2018"

[dependencies]
ntree = { git = "https://github.com/fefit/ntree", tag = "v0.0.1" }
rphtml = { git = "https://github.com/fefit/rphtml", tag = "v0.3.0" }